### ISSUE TITLE
Class cast exception in version 3.8.0

### ISSUE THREAD

**Issue by kapcsandi** [NAXAM/xam-okhttp3#1]
Please update the binding version to a more recent one because the current version (3.8.0) has an issue (https://github.com/square/okhttp/issues/3804) which was fixed in version 3.9.1.
Thanks in advance!

**Comment by tuyen-vuduc** [comment]
Plz don't use this binding library. It's duplicated with [OkHttp3](https://www.nuget.org/packages/Square.OkHttp3/). I have made PR for v3.9.1, but no response from the author of that library yet.

In the mean while, you could use my feed [here](https://www.myget.org/feed/naxam/package/nuget/Square.OkHttp3).

Cheers.
